site_name: AWS Lambda Events
site_description: AWS Lambda Events
site_author: Michael Brewer
repo_name: michaelbrewer/aws-lambda-events
repo_url: https://github.com/michaelbrewer/aws-lambda-events
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - git-revision-date
  - search

extra:
  analytics:
    provider: google
    property: UA-191564964-1
