site_name: AWS Lambda Events
site_description: AWS Lambda Events
site_author: Michael Brewer
repo_name: aws-lambda-events
repo_url: https://github.com/aphextwinz/aws-lambda-events
edit_uri: edit/main/docs/

theme:
  name: material
  logo: media/aws-logo-light.svg
  favicon: media/aws-lambda-1.svg
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - tables
  - meta
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - git-revision-date
  - search

extra:
  analytics:
    provider: google
    property: G-PM4TKP5NNF

nav:
  - Overview:
    - index.md
    - lambda-resources.md
    - lambda-context.md
    - lambda-lifecycle.md
  - AWS Lambda Events:
    - http-api.md
    - http-api-custom-authorizer.md
    - rest-api.md
    - rest-api-custom-authorizer.md
    - function-url.md
    - alexa-skills-kit.md
    - alexa-smart-home.md
    - alb.md
    - appsync-resolver.md
    - appsync-authorizer.md
    - cloudformation.md
    - cloudfront-function.md
    - cloudfront-lambda-edge.md
    - cloudwatch-logs.md
    - code-commit.md
    - code-pipeline-job.md
    - cognito-events.md
    - cognito-user-pool.md
    - config.md
    - connect.md
    - dynamodb.md
    - event-bridge.md
    - iot-events.md
    - iot.md
    - apache-kafka.md
    - kinesis-firehose.md
    - kinesis-streams.md
    - lex.md
    - lex-v2.md
    - mq.md
    - amazon-msk.md
    - s3.md
    - s3-batch.md
    - s3-object-lambda.md
    - secrets-manager.md
    - ses.md
    - sns.md
    - sqs.md
    - work-mail.md
  - build-project.md
