[tool.poetry]
name = "lambda-event-schema-tool"
version = "0.1.0"
description = "Creating Shareable test events"
authors = ["Michael Brewer"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.21.23"
pick = "^1.2.0"

[tool.poetry.dev-dependencies]
setuptools = "^60.10.0"
isort = "^5.10.1"
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
