name: ci 
on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/ci.yml'
      - 'docs/*'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install latest pip
      run: pip install -U pip

    - name: Install mkdocs dependencies
      run: make dev

    - name: Deploy to github pages
      run: mkdocs gh-deploy --force
