name: aws-lambda-publish-shared-event
on:
  push:
    branches: 
      - master
      - main
    paths:
      - event-schemas/*
      - docs/events/*
      - .github/workflows/python.yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install wheel
      working-directory: event-schema
      run: pip3 install wheel

    - name: Install dependencies
      working-directory: event-schema
      run: make dev

    - name: Run test suite
      working-directory: event-schema
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          file: ./event-schema/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
